#!/bin/bash
#
# dmymailsrv    Dummy Mail Receiver
#
# Author:       ITO Nobuaki <daydream.trippers@gmail.com>
#
# chkconfig:    345 97 03
#
# description:  This is a daemon which saves all mail messages.
# processname:  dmymailsrv
#

### BEGIN INIT INFO
# Provides: dmymailsrv
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Dummy mail receiver
# Description: Daemon which saves all mail messages.
### END INIT INFO


# source function library
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/dmymailsrv ]; then
	. /etc/sysconfig/dmymailsrv
fi

RETVAL=0
prog=dmymailsrv

start() {
	echo -n $"Starting dmymailsrv: "
	daemon +10 "dmymailsrv $OPTIONS &"
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/dmymailsrv
}

stop() {
	echo -n $"Stopping dmymailsrv: "
	killproc dmymailsrv
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/dmymailsrv
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  condrestart|try-restart)
	[ -f /var/lock/subsys/dmymailsrv ] && restart
	;;
  status)
	status dmymailsrv
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL
